_wandb:
    value:
        cli_version: 0.23.1
        e:
            cacbr8uffmv558xx907axppxl7wrjfwy:
                args:
                    - --data_dir
                    - ./pretrain_data_bc
                    - --output_dir
                    - ./bc_checkpoints
                    - --num_workers
                    - "0"
                codePath: pretrain_bc.py
                codePathLocal: pretrain_bc.py
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "728249831424"
                        used: "48030367744"
                email: liuminghao491@gmail.com
                executable: /environment/miniconda3/envs/lab/bin/python
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-c10a9e27-4d6a-bc2d-9169-029a8ab60d50
                host: featurize
                memory:
                    total: "58965086208"
                os: Linux-5.15.0-105-generic-x86_64-with-glibc2.35
                program: /home/featurize/Chinese-Standard-Mahjong/pretrain_bc.py
                python: CPython 3.14.2
                root: /home/featurize/Chinese-Standard-Mahjong
                startedAt: "2025-12-23T06:56:27.275017Z"
                writerId: cacbr8uffmv558xx907axppxl7wrjfwy
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.14.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 1024
data_dir:
    value: ./pretrain_data_bc
device:
    value: cuda
epochs:
    value: 10
hidden_dim:
    value: 256
lr:
    value: 0.001
model_type:
    value: full
no_wandb:
    value: false
num_workers:
    value: 0
output_dir:
    value: ./bc_checkpoints
resume:
    value: null
save_interval:
    value: 1
use_vec:
    value: true
val_data_dir:
    value: null
wandb_name:
    value: null
wandb_project:
    value: mahjong-pretrain
weight_decay:
    value: 0.0001
